Issue #398
ukmo-waves/WW3 pull request #28
Opened 2021-06-02 15:11 UTC by ukmo-juan-castillo

# Pull Request Summary
Some comments and rearrangement of the calculation for variable NRQMAX so that it is more easily understood.

## Description
This PR adds some comments in the code describing what NRQMAX is and how it should be calculated. It also splits the calculation of this variable in output groups, one per line, so that it is more easily understood. No changes in results are expected, although the right value of NRQMAX was recalculated and changes slightly, as the group 2 supposedly contains 19 scalars but only 18 MPI communicators are needed.

### Issue(s) addressed
This is just a small enhancement to improve clarity in the code, in particular on how NRQMAX is calculated. The code should be in general quite insensitive to this value unless a large amount of output fields are written to file.

- fixes #398
- fixes noaa-emc/ww3/issues/398

### Check list  
* Is your feature branch up to date with the authoritative repository (NOAA/develop)?
YES
* Make sure you have checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop), [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop) and [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number)
DONE
* Reviewers: @aliabdolali @ukmo-ccbunney 

### Testing
* How were these changes tested?
Not tested, as the changes were cosmetic
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
NO - there may be only problems when writing to file all or most of all the output fields available
* If a new feature was added, was a new regression test added?
N/A
* Have regression tests been run?
NO
* Which compiler / HPC you used to run the regression tests in the PR? 
N/A
* Please provide the summary output of matrix.comp (_matrix.Diff.out_, _matrixCompFull.out_ and _matrixCompSummary.out_):    
N/A
Please indicate the expected changes in the outputs ([excluding the known list of non-identical tests](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-master#4-look-at-results)).
NONE

2021-06-02 16:22 UTC, ukmo-ccbunney requested changes
That's great - just one request.

2021-06-02 16:22 UTC, ukmo-ccbunney commented on model/ftn/w3initmd.ftn
> +! NRQMAX is calculated as the sum of all fields described before (Hs)
@ukmo-juan-castillo  That's much clearer! Nice one.

Can you just add one comment to explain why most of group 1 is not counted.

2021-06-02 16:38 UTC, ukmo-ccbunney approved these changes

2021-06-10 17:31 UTC, aliabdolali approved these changes

2021-06-11 08:58 UTC, merged