MO hybrid features update.
ukmo-waves/WW3 pull request #3
Opened 2019-12-03 15:56 UTC by ukmo-jianguo-li

Updated atomic lines and hybrid MPI_INIT_THREAD

2019-12-10 10:56 UTC, ukmo-ccbunney commented
@ukmo-jianguo-li can you please run a regression test (`ww3_tp2.10` would be obvious choice) on your branch to ensure your changes don't have any unintended side effects ? This should be compared against the output of the same regression test run under the **develop** branch.

Also, I think it would be worthwhile updating the MPI_INIT statement in `ww3_multi.ftn` in addition to `ww3_shel.ftn` as both can be run in hybrid mode.

2020-02-25 14:30 UTC, ukmo-ccbunney commented
> 
> 
> Updated atomic lines and hybrid MPI_INIT_THREAD

The MPI_INIT_THREAD changes have been moved to a new PR #4

2020-03-11 09:23 UTC, ukmo-ccbunney commented
@CarstenHansen - would you be willing to review this PR? Most of the changes are in the the w3psmcmd module; it might be easier to view the changes for that file via the two separate commits (a lot of the changes were to fix an incorrectly specified switch).

2020-03-11 11:53 UTC, ukmo-ccbunney commented
Results of regtests (ww3_tp2.10 and ww3_tp.216) attached.

Small differences in grid and point output due to reordering some code and rearranging some terms to allow atomic access.

Multiple runs of the new hybrid regtests (MPI_OMPH) show identical results using B4B flag.

[matrixCompSummary.zip](https://github.com/ukmo-waves/WW3/files/4318063/matrixCompSummary.zip)

2020-03-11 12:23 UTC, CarstenHansen commented
Hi Chris and @ukmo-jianguo-li. I will try to review this PR. Although I have no practical experience with the SMC grids and have only sporadic knowledge about OpenMP, I will consult the Spatial Propagation section in the WW3 User Manual and the OpenMP 5.0 Specification on [https://www.openmp.org](https://www.openmp.org).

2020-03-11 12:59 UTC, ukmo-ccbunney commented
Thanks @CarstenHansen. I have invited you as an external collaborator to our WW3 Repo - this will allow me to formally add you as a reviewer once you accept the invitation. I have also done the same for @RobertoPadilla-NOAA

2020-03-11 13:07 UTC, ukmo-ccbunney commented
By the way - if you agree with the addition of the `B4B` switch, then we will add a commit to update the manual accordingly.

2020-03-11 16:59 UTC, CarstenHansen reviewed
Introduction of the B4B switch is a good idea as long as the side gradients are much larger than 1.e-6 m/s. I believe this is the case for the regression tests, and I believe the B4B switch will not be applied for a large-scale model.

2020-03-12 11:54 UTC, CarstenHansen requested changes
There are two more lines where I think _x operator expr_  should be changed to _x operator (expr)_. See my comments in commit e2cfc986019572f5e96acf580a7a83268c2b23d9

2020-03-12 11:54 UTC, CarstenHansen commented on model/ftn/w3psmcmd.ftn
> +              AFCN(M) = AFCN(M) - (FUMD(i)*UCFL(M) - FUDIFX(i))
Do you know that without the parentheses the first difference might be evaluated first and be stored in the memory of AFCN(M)? In that case, AFCN(M) would be updated twice, and I believe the OpenMP routines may miss one of the updates. The order of evaluation in lines 482 and 632 must also be changed.

EDIT: The parentheses are indeed required according to an [Intel® Fortran Compiler 19.1 Developer Guide and Reference](https://software.intel.com/en-us/fortran-compiler-developer-guide-and-reference-atomic). One of the rules that applies to an update-statement is:
"_x operator expr_ must be mathematically equivalent to _x operator (expr)_. This requirement is satisfied if the operators in expr have precedence greater than operator, or by using parentheses around expr or subexpressions of expr."

2020-03-12 11:54 UTC, CarstenHansen commented on model/ftn/w3psmcmd.ftn
>                AFCN(N) = AFCN(N) + FUMD(i)*UCFL(N) - FUDIFX(i)
Change _x operator expr_  to _x operator (expr)_:             AFCN(N) = AFCN(N) + ( FUMD(i)*UCFL(N) - FUDIFX(i) )

2020-03-12 11:54 UTC, CarstenHansen commented on model/ftn/w3psmcmd.ftn
>                AFCN(M) = AFCN(M) + FUMD(i)*UCFL(M)*FMR - FUDIFX(i)
Change _x operator expr_  to _x operator (expr)_: AFCN(M) = AFCN(M) + ( FUMD(i)*UCFL(M)*FMR - FUDIFX(i) )

2020-03-13 09:16 UTC, ukmo-jianguo-li commented
All,
It is no harm to add the parentheses for the calculations, at least on our supercomputer, if other compilers require.  I have done that in my test branch and tested with our UK 1.5-3km model. The results are identical to those without the parentheses.
Kind regards.
Jian-Guo

From: Carsten Hansen <notifications@github.com>
Sent: 12 March 2020 11:55
To: ukmo-waves/WW3 <WW3@noreply.github.com>
Cc: Li, JianGuo <jianguo.li@metoffice.gov.uk>; Mention <mention@noreply.github.com>
Subject: Re: [ukmo-waves/WW3] MO hybrid features update. (#3)


@CarstenHansen requested changes on this pull request.

There are two more lines where I think x operator expr should be changed to x operator (expr). See my comments in commit e2cfc98<https://github.com/ukmo-waves/WW3/commit/e2cfc986019572f5e96acf580a7a83268c2b23d9>

________________________________

In model/ftn/w3psmcmd.ftn<https://github.com/ukmo-waves/WW3/pull/3#discussion_r391536930>:

>                  FCNt(M) = FCNt(M) - FUTRN*CTRNX(N)*CTRNX(M)



               ENDIF



 !  Also divided by another cell length as UCFL is in basic unit.



-!/OMPG!$OMP ATOMIC



-              AFCN(M) = AFCN(M) - FUMD(i)*UCFL(M) + FUDIFX(i)



+!/OMPG/!$OMP ATOMIC



+              ! ChrisB: Re-arranged the RHS term below to make it



+              ! valid for OMP ATMOIC directive.



+              AFCN(M) = AFCN(M) - (FUMD(i)*UCFL(M) - FUDIFX(i))



Do you know that without the parentheses the first difference might be evaluated first and be stored in the memory of AFCN(M)? In that case, AFCN(M) would be updated twice, and I believe the OpenMP routines may miss one of the updates. The order of evaluation in lines 482 and 632 must also be changed.

EDIT: The parentheses are indeed required according to an Intel® Fortran Compiler 19.1 Developer Guide and Reference<https://software.intel.com/en-us/fortran-compiler-developer-guide-and-reference-atomic>. One of the rules that applies to an update-statement is:
"x operator expr must be mathematically equivalent to x operator (expr). This requirement is satisfied if the operators in expr have precedence greater than operator, or by using parentheses around expr or subexpressions of expr."

________________________________

In model/ftn/w3psmcmd.ftn<https://github.com/ukmo-waves/WW3/pull/3#discussion_r391539547>:

>                  FCNt(N) = FCNt(N) + FUTRN*CTRNX(N)



               ENDIF



 !  Also divided by another cell length as UCFL is in basic unit.



-!/OMPG!$OMP ATOMIC



+!/OMPG/!$OMP ATOMIC



               AFCN(N) = AFCN(N) + FUMD(i)*UCFL(N) - FUDIFX(i)



Change x operator expr to x operator (expr): AFCN(N) = AFCN(N) + ( FUMD(i)*UCFL(N) - FUDIFX(i) )

________________________________

In model/ftn/w3psmcmd.ftn<https://github.com/ukmo-waves/WW3/pull/3#discussion_r391546368>:

>                  FCNt(M) = FCNt(M) + FUTRN*CTRNX(M)



               ENDIF



-!/OMPG!$OMP ATOMIC



+!/OMPG/!$OMP ATOMIC



               AFCN(M) = AFCN(M) + FUMD(i)*UCFL(M)*FMR - FUDIFX(i)



Change x operator expr to x operator (expr): AFCN(M) = AFCN(M) + ( FUMD(i)*UCFL(M)*FMR - FUDIFX(i) )

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/ukmo-waves/WW3/pull/3#pullrequestreview-373448289>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ANGV3EGXRROOHGZ25X2MGFLRHDEPPANCNFSM4JU2K37Q>.

2020-03-17 09:24 UTC, ukmo-ccbunney commented
@aliabdolali - would you be willing to review this PR?

2020-03-20 14:18 UTC, aliabdolali commented
@ukmo-ccbunney Have you compared the entire regression test or just tp2.10 and tp2.16? If you believe it still do not affect the rest of the code, it is a necessity to have the entire suite comparison. I like the idea of B4B swtich, have you added the description in the manual for it? 
Happy Nowruz. 
AA

2020-03-20 14:31 UTC, ukmo-ccbunney commented
Ali, Happy Nowruz too :) 

> 
> Have you compared the entire regression test or just tp2.10 and tp2.16?

I have just performed regtests for tp2.10 and tp2.16 as these are the only regtests that use the SMC module. I was assuming that the full regtest suite would be run at the point where I raise a PR to have our UKMO 'develop' branch merged with NOAA's. I can run a full suite if you prefer. This procedure is something that we might want to make clearer in our "review framework for trusted institutional forks" document. @ajhenrique - any comment on this?

>
> I like the idea of B4B swtich, have you added the description in the manual for it?

I have - I was just waiting for the reviews to agree that it was a good idea, then I intended to push the commit with the manual addition. Since you also agree it is worthwhile, I will push that change up now.

Cheers,
Chris.

2020-03-20 14:33 UTC, ukmo-ccbunney commented
@aliabdolali and @CarstenHansen  - I've pushed a final commit that documents the `B4B` switch in the manual. Thanks both.

2020-03-20 14:58 UTC, aliabdolali approved these changes

2020-03-20 15:03 UTC, CarstenHansen approved these changes

2020-03-30 10:24 UTC, ukmo-ccbunney commented
Full regtest results attached.

Summary: small differences to the SMC regtests only (ww3_tp2.10 and ww3_tp2.16); these are expected due to rearrangement of some terms to allow for ATOMIC access.

Max absolute difference in output Hs fields: 4.2143278e-05m and 5.9604645e-08m for ww3_tp2.10 and ww3_tp2.16 respectively.

[matrixCompSummary_openmp.zip](https://github.com/ukmo-waves/WW3/files/4402114/matrixCompSummary_openmp.zip)

2020-03-30 10:25 UTC, merged

2020-03-30 10:42 UTC, ukmo-jianguo-li commented
Merged #3<https://github.com/ukmo-waves/WW3/pull/3> into develop.
Does this mean we can delete the fb_openmp branch now?   This is also a test of github recorded reply by email.

2020-03-30 10:49 UTC, ukmo-jianguo-li commented
Well done!  I will clear my fb_branch copy from the desktop disk.  By the way, reply by email is tested fine as long as you tidy it up before hitting the send button.

2020-03-30 12:54 UTC, ukmo-ccbunney commented
@ukmo-jianguo-li 
>Does this mean we can delete the fb_openmp branch 

Yes - you can! Remember, just deleting the repository from your local disk does not delete the branch from the GitHub repo. Feel free to clean up your local repo and I will delete the branch from our origin on GitHub.