Added boundary checks to the SMC grid input files for ww3_grid,
ukmo-waves/WW3 pull request #6
Opened 2020-06-18 08:21 UTC by UKMO-lsampson

Added boundary checks to the SMC grid input files for ww3_grid, to ensure they comply with the limits of the nameslist.

Regrestion tests complete:
- ww3_tp2.10 [No changes to results]
- ww3_tp2.16 [No changes to results]

2020-06-19 07:32 UTC, ukmo-ansaulter reviewed
Thanks Lewis,

I'm generally happy - although note that you've had to use EXIT(65) here rather than EXTCDE(65) in order to make the exit and error messaging work cleanly. If you could just summarize that reasoning in the comments, so we have it captured, then I'm good to approve.

Cheers
Andy

2020-06-19 08:55 UTC, UKMO-lsampson commented
> Thanks Lewis,
> 
> I'm generally happy - although note that you've had to use EXIT(65) here rather than EXTCDE(65) in order to make the exit and error messaging work cleanly. If you could just summarize that reasoning in the comments, so we have it captured, then I'm good to approve.
> 
> Cheers
> Andy

Hi Andy, 

Thanks for bringing this to my attention, the change was for an earlier practice with the code and has now been reverted back to EXTCDE instead of EXIT. This has been updated in the latest git commit. 

Best regards, Lewis.

2020-06-19 08:57 UTC, ukmo-ansaulter commented
> > Thanks Lewis,
> > I'm generally happy - although note that you've had to use EXIT(65) here rather than EXTCDE(65) in order to make the exit and error messaging work cleanly. If you could just summarize that reasoning in the comments, so we have it captured, then I'm good to approve.
> > Cheers
> > Andy
> 
> Hi Andy,
> 
> Thanks for bringing this to my attention, the change was for an earlier practice with the code and has now been reverted back to EXTCDE instead of EXIT. This has been updated in the latest git commit.
> 
> Best regards, Lewis.

That looks good now Lewis, I'll approve

2020-06-19 09:02 UTC, ukmo-ansaulter approved these changes

2020-06-25 13:10 UTC, aliabdolali approved these changes
It looks ok to me.

2020-06-29 15:23 UTC, ukmo-ccbunney requested changes
Hi Lewis,
Looking at this, I wonder if we could make the error message slightly clearer.
It would also be nice to include ISEA so the user can see exactly which line caused the issue.
I think something like this would be better:

```
 *** WAVEWATCH-III ERROR IN W3GRID
  SMC CELL LONGITUDE RANGE OUTSIDE BASE GRID RANGE:
  ISEA = XXX; IX = XXX:XXX; NX = XXX
```
and similarly for latitude.

This would require you to provide some extra parameters to the write statement, i.e. on line 4415:
```
WRITE (NDSE,1014) ISEA, IX, IX+IK-1, NX
```

2020-06-30 11:31 UTC, ukmo-ccbunney approved these changes

2020-06-30 11:32 UTC, merged